siraj_dbt:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-37101eca-831e.cloud.databricks.com
      http_path: /sql/1.0/warehouses/04f936abe43b34e0
      schema: default

      threads: 1
      type: databricks
    prod:
      catalog: dbt_tutorial_prod
      host: dbc-37101eca-831e.cloud.databricks.com
      http_path: /sql/1.0/warehouses/04f936abe43b34e0
      schema: default

      threads: 1
      type: databricks
  target: dev
